version: "3.8"
services:
  db:
    container_name: postgres-server
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    networks:
      - postgres-network
  pgAdmin:
    container_name: pgAdmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    networks:
      - postgres-network
    depends_on:
      - db
    ports:
      - "5050:80"

networks:
  postgres-network:
    driver: bridge
